# Generated by Django 5.0.7 on 2025-09-28 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_dailyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitReport',
            fields=[
            ],
            options={
                'verbose_name': 'Profit Report',
                'verbose_name_plural': 'Profit Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin_panel.managerchat',),
        ),
    ]
