# Generated by Django 5.0.7 on 2025-09-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_categorydescription_manualcategory_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['serial_number', 'price', 'title']},
        ),
        migrations.AddField(
            model_name='folder',
            name='description',
            field=models.TextField(blank=True, help_text='Optional. If set, this will be shown inside this folder in the bot.', verbose_name='Custom Description'),
        ),
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.PositiveIntegerField(default=100, help_text='Used for sorting items in the bot. Lower number comes first.', verbose_name='Serial Number'),
        ),
    ]
