# Generated by Django 5.0.7 on 2025-09-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_alter_item_options_folder_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buying_cost',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='The cost price of the item for profit calculation.', max_digits=10, null=True, verbose_name='Buying Cost'),
        ),
    ]
