# Generated by Django 5.0.7 on 2025-09-29 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_item_buying_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Region Name')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FreeFireItem',
            fields=[
            ],
            options={
                'verbose_name': 'Free Fire Item',
                'verbose_name_plural': 'Free Fire Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('items.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='provider_item_id',
            field=models.IntegerField(blank=True, help_text='The unique ID of the item from the external provider (e.g., Shop2TopUp).', null=True, unique=True, verbose_name='Provider Item ID'),
        ),
        migrations.AlterField(
            model_name='categorydescription',
            name='category',
            field=models.CharField(choices=[('pubg_uc', 'PUBG UC'), ('codes', 'GIFTCARDS & CODES'), ('popularity', 'Popularity'), ('home_vote', 'HOME VOTE'), ('offers', 'Offers'), ('giftcard', 'Giftcard'), ('stars', 'Telegram Stars'), ('diamond', 'Mobilelegends diamond'), ('more_pubg', 'More PUBG Services'), ('free_fire', 'Free Fire')], max_length=50, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='category',
            field=models.CharField(blank=True, choices=[('pubg_uc', 'PUBG UC'), ('codes', 'GIFTCARDS & CODES'), ('popularity', 'Popularity'), ('home_vote', 'HOME VOTE'), ('offers', 'Offers'), ('giftcard', 'Giftcard'), ('stars', 'Telegram Stars'), ('diamond', 'Mobilelegends diamond'), ('more_pubg', 'More PUBG Services'), ('free_fire', 'Free Fire')], max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('pubg_uc', 'PUBG UC'), ('codes', 'GIFTCARDS & CODES'), ('popularity', 'Popularity'), ('home_vote', 'HOME VOTE'), ('offers', 'Offers'), ('giftcard', 'Giftcard'), ('stars', 'Telegram Stars'), ('diamond', 'Mobilelegends diamond'), ('more_pubg', 'More PUBG Services'), ('free_fire', 'Free Fire')], max_length=50, verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='FreeFireRegionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup', models.DecimalField(decimal_places=2, default=0.0, help_text='The amount to add to the base provider price.', max_digits=10, verbose_name='Markup ($)')),
                ('final_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Final Price')),
                ('is_active', models.BooleanField(default=True, help_text='If unchecked, this item will not be shown for this region in the bot.', verbose_name='Is Active')),
                ('item', models.ForeignKey(limit_choices_to={'category': 'free_fire'}, on_delete=django.db.models.deletion.CASCADE, related_name='freefire_prices', to='items.item', verbose_name='Free Fire Item')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freefire_prices', to='items.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Free Fire Region Price',
                'verbose_name_plural': 'Free Fire Region Prices',
                'ordering': ['region__name'],
                'unique_together': {('item', 'region')},
            },
        ),
    ]
