# Generated by Django 5.0.7 on 2025-09-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_region_freefireitem_item_provider_item_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['display_name'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AddField(
            model_name='region',
            name='description',
            field=models.TextField(blank=True, help_text='This text will be shown in the bot after selecting this region.', null=True, verbose_name='Region Description'),
        ),
        migrations.AddField(
            model_name='region',
            name='display_name',
            field=models.CharField(default='', help_text='The name that users will see in the bot (e.g., Russia 🇷🇺, Europe 🇪🇺).', max_length=100, verbose_name='Display Name in Bot'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(help_text='The exact region name from the API (e.g., RU, CIS, EUROPE).', max_length=50, unique=True, verbose_name='API Region Name'),
        ),
    ]
