# Generated by Django 5.0.7 on 2025-09-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_alter_region_options_region_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeFireRegion',
            fields=[
            ],
            options={
                'verbose_name': 'Free Fire Region',
                'verbose_name_plural': 'Free Fire Regions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('items.region',),
        ),
    ]
