# Generated by Django 5.0.7 on 2025-12-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_freefireregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='activator',
            field=models.CharField(blank=True, choices=[('kokos', 'Kokos'), ('fars', 'FARS'), ('smileone', 'SmileOne'), ('ucodeium', 'UCodeium'), ('midasbuy', 'Midasbuy')], help_text='if not selected, then manual activation', null=True, verbose_name='Activator'),
        ),
    ]
