# Generated by Django 5.0.7 on 2025-09-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0007_activatorpriority_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='buying_cost',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='The cost price of this specific code.', max_digits=10, null=True, verbose_name='Buying Cost'),
        ),
        migrations.AddField(
            model_name='stockblecode',
            name='buying_cost',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='The cost price of this specific code.', max_digits=10, null=True, verbose_name='Buying Cost'),
        ),
        migrations.AddField(
            model_name='uccode',
            name='buying_cost',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='The cost price of this specific code.', max_digits=10, null=True, verbose_name='Buying Cost'),
        ),
    ]
