# Generated by Django 5.0.7 on 2025-12-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0008_giftcard_buying_cost_stockblecode_buying_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activatorpriority',
            name='name',
            field=models.CharField(choices=[('kokos', 'Kokos'), ('fars', 'FARS'), ('smileone', 'SmileOne'), ('ucodeium', 'UCodeium'), ('midasbuy', 'Midasbuy')], max_length=20, unique=True, verbose_name='Activator Name'),
        ),
        migrations.AlterField(
            model_name='uccode',
            name='activator',
            field=models.CharField(blank=True, choices=[('kokos', 'Kokos'), ('fars', 'FARS'), ('smileone', 'SmileOne'), ('ucodeium', 'UCodeium'), ('midasbuy', 'Midasbuy')], help_text='Filled automatically after successful activation', null=True, verbose_name='Successful Activator'),
        ),
    ]
