# Generated by Django 5.0.7 on 2025-09-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_topup_currency_topup_payment_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='player_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Player Name'),
        ),
        migrations.AddField(
            model_name='order',
            name='provider_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Provider Transaction ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('pubg_uc', 'PUBG UC'), ('codes', 'GIFTCARDS & CODES'), ('popularity', 'Popularity'), ('home_vote', 'HOME VOTE'), ('offers', 'Offers'), ('giftcard', 'Giftcard'), ('stars', 'Telegram Stars'), ('diamond', 'Mobilelegends diamond'), ('more_pubg', 'More PUBG Services'), ('free_fire', 'Free Fire')], verbose_name='Category'),
        ),
    ]
